# action.yml
name: '42Crunch REST API Static Security Testing'
description: 'The REST API Static Security Testing action adds an automatic static application security testing (SAST) to your workflows'
inputs:
  api-token:
    description: 'The API token to access 42Crunch Platform.'
    required: true
  collection-name:
    description: 'The API token to access 42Crunch Platform.'
    required: true
    default: 'github'
  min-score:
    description: 'Minimum score for OpenAPI files.'
    required: true
    default: '75'
branding:
  icon: 'eye'  
  color: 'purple'
runs:
  using: 'docker'
  image: 'Dockerfile'
