- name: 42Crunch REST API Static Security Testing
  # You may pin to the exact commit or the version.
  # uses: 42Crunch/api-security-audit-action@e2aac9b82856dbfc9fce9d27cdacb702b0479022
  uses: 42Crunch/api-security-audit-action@v2
  with:
    # The API token to access 42Crunch Platform. Please create free account at https://platform.42crunch.com/register and follow hese steps to configure API_TOKEN https://docs.42crunch.com/latest/content/tasks/integrate_github_actions.htm
    api-token: # optional
    # Minimum score for OpenAPI files.
    min-score: # optional, default is 75
    # 42Crunch platform URL
    platform-url: # optional, default is https://platform.42crunch.com
    # Log level, one of: FATAL, ERROR, WARN, INFO, DEBUG
    log-level: # optional, default is INFO
    # Share new API collections with everyone, one of: OFF, READ_ONLY, READ_WRITE
    share-everyone: # optional, default is OFF
    # GitHub token for uploading results to Github Code Scanning
    github-token: # optional, default is ${{ github.token }}
    # Upload results to Github Code Scanning
    upload-to-code-scanning: # optional, default is false
    # Do not fail the action even if the faiures were detected in the API contract
    ignore-failures: # optional, default is false
